services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./files:/var/www/files
      - ./logs:/var/www/logs
      - ./src:/var/www/html
      - ./configs.json:/var/www/configs.json
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_PORT: 3306
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data: